### create book
POST localhost:8080/book/create
Content-Type:application/json

{
  "title": "Ikki eshik orasi",
  "author": "O'tkir Hoshimov"
}
### get book list
GET localhost:8080/book/list
### get book by id
GET localhost:8080/book/get/10
### delete by id
DELETE localhost:8080/book/delete/1
### update by id
PUT  localhost:8080/book/update/9
Content-Type: application/json

{
  "title": "Kecha va Kunduz ",
  "author": "Cho'lpon ",
  "publishYear": 1936
}


### Student
### create student
POST  localhost:8080/student/create1
Content-Type: application/json

{
  "name": "Mahmud",
  "surname": "Mahmudov",
  "phone": "998909038923"
}


### student list
GET localhost:8080/student/list
### get student by id
GET localhost:8080/student/get/3
### delete student by id
DELETE localhost:8080/student/delete/3
### update student by id
PUT localhost:8080/student/update/3
Content-Type: application/json

{
    "phone": "998998768516"
}

### Student Book
### create student book
POST localhost:8080/student_book/create
Content-Type: application/json

{
  "student": {
    "id": 5
  },
  "book": {
    "id": 4
  }
}

### student book list
GET localhost:8080/student_book/list
### get student book by id
GET localhost:8080/student_book/7
### get student list who get book
GET localhost:8080/student_book/student/list
### get taken book list
GET localhost:8080/student_book/book/list

