### create book
POST localhost:8080/book/create
Content-Type:application/json

{
  "title": "Kecha va kunduz",
  "author": "Cho'lpon",
  "publishYear": "1933"
}
### get book list
GET localhost:8080/book/list
### get book by id
GET localhost:8080/book/list/8
### delete by id
DELETE localhost:8080/book/delete/8
### update by id
PUT  localhost:8080/book/update/9
Content-Type: application/json

{
  "title": "Kecha va Kunduz ",
  "author": "Cho'lpon ",
  "publishYear": 1936
}